# Generated by Django 6.0.3 on 2026-05-01 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_displayname'),
        ('localevents', '0004_event_event_capacity_event_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_on',
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together={('user_registrant', 'event')},
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='localevents.event'),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='user_registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='new_registrant',
        ),
    ]
