# Generated by Django 6.0.3 on 2026-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_roles_alter_role_name'),
        ('localevents', '0007_alter_event_status_alter_event_title_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventsignup',
            constraint=models.UniqueConstraint(fields=('user_registrant', 'event'), name='unique_user_event_signup'),
        ),
    ]
