# Generated by Django 6.0.3 on 2026-05-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0008_eventsignup_unique_user_event_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name']},
        ),
    ]
