# Generated by Django 6.0.1 on 2026-05-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_book_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_year']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='availableToBorrow',
            new_name='available_to_borrow',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publicationYear',
            new_name='publication_year',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updatedOn',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='dateBookmarked',
            new_name='date_bookmarked',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='anonReviewer',
            new_name='anon_reviewer',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='userReviewer',
            new_name='user_reviewer',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='dateBorrowed',
            new_name='date_borrowed',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='dateToReturn',
            new_name='date_to_return',
        ),
    ]
