# Generated by Django 6.0.2 on 2026-05-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_profile_displayname_profile_roles'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='commissiontype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='commission',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions_profile', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.commissiontype'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='people_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('manpower_required', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full')], default='open', max_length=20)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission')),
            ],
            options={
                'ordering': [models.Case(models.When(status='open', then=models.Value(0)), models.When(status='full', then=models.Value(1)), output_field=models.IntegerField()), '-manpower_required', 'role'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplications_profile', to='accounts.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplications', to='commissions.job')),
            ],
            options={
                'ordering': [models.Case(models.When(status='pending', then=models.Value(0)), models.When(status='accepted', then=models.Value(1)), models.When(status='rejected', then=models.Value(2)), output_field=models.IntegerField()), '-applied_on'],
            },
        ),
    ]
