# Generated by Django 6.0.2 on 2026-03-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='commissiontype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='commissions.commissiontype'),
        ),
    ]
