# Generated by Django 6.0.2 on 2026-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Book Contributor', 'Book Contributor'), ('Project Creator', 'Project Creator'), ('Commission Maker', 'Commission Maker')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayName',
            field=models.CharField(max_length=63),
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='accounts.role'),
        ),
    ]
