# Generated by Django 6.0.1 on 2026-05-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Reader', 'Reader'), ('Book Contributor', 'Book Contributor')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(related_name='profiles', to='accounts.role'),
        ),
    ]
