# Generated by Django 6.0.2 on 2026-05-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_profile_displayname_profile_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='emailAddress',
            new_name='email_address',
        ),
    ]
