# Generated by Django 6.0.1 on 2026-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Book Contributor', 'Book Contributor')], default='Reader', max_length=50),
        ),
    ]
