# Generated by Django 6.0.1 on 2026-05-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
        ('accounts', '0004_alter_profile_roles_alter_role_name'),
    ]

    operations = [
    ]
