# Generated by Django 6.0.2 on 2026-05-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_id'),
        ('accounts', '0004_alter_profile_roles_alter_role_name'),
    ]

    operations = [
    ]
