# Generated by Django 6.0.2 on 2026-05-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
        ('accounts', '0005_merge_20260504_2357'),
    ]

    operations = [
    ]
