# Generated by Django 6.0.1 on 2026-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260504_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Book Contributor', 'Book Contributor'), ('Project Creator', 'Project Creator'), ('Commission Maker', 'Commission Maker')], max_length=50, unique=True),
        ),
    ]
