# Generated by Django 6.0.2 on 2026-05-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0003_profile_role_0005_merge_20260504_2357'),
        ('accounts', '0006_remove_profile_role_alter_role_name'),
    ]

    operations = [
    ]
