# Generated by Django 5.2.12 on 2026-03-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0002_alter_project_options_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Project categories'},
        ),
    ]
