# Generated by Django 6.0.2 on 2026-05-05 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0002_project_creator_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
