# Generated by Django 6.0.2 on 2026-05-01 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_displayname'),
        ('diyprojects', '0005_alter_project_options_project_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_favorited', models.DateField(auto_now_add=True)),
                ('project_status', models.CharField(choices=[('Backlog', 'Backlog'), ('To-Do', 'To-Do'), ('Done', 'Done')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diyprojects.project')),
            ],
        ),
    ]
